[package]
name = "rate-limit"
version = "0.2.0"
edition = "2024"

[lib]
name="rate_limit"

[dependencies]
chrono = "0.4.40"
derive_more = { version = "1.0.0", features = ["from"] }
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["time"] }
